### ISSUE TITLE
permettre le numérotage des pages d'un ebook

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki-extension-publication#10]
Prévoir un param a activer dans l'ebook permettant le placement automatique d'une numérotation de pages (hors couvertures)

**Comment by oncletom** [comment]
Dac. En milieu de bas de page ?

Quid des autres formats (paysage, portrait, A4, A5) ?

**Comment by mrflos** [comment]
je vous laisse voir ce point, pas d'avis sur le comportement par défaut, j’espère juste qu'on pourra customiser les css pour changer la position  ;)

**Comment by gatienbataille** [comment]
pas trop d'importance pour moi et peut-être que ceci peut-être un des param évoqués dans #12
