### ISSUE TITLE
Meilleure gestion de l'appel à la librairie chromium

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki-extension-publication#11]
Actuellement, il n'y pas pas de tests pour savoir si le wiki qui appelle possède la librairie chromium. 
L'idée serait que si elle n'est pas présente, on puisse l'appeler via le serveur coop.tools

**Comment by oncletom** [comment]
Bonne idée.

Est-ce qu'on indique "quelque part" que la librairie chromium telle que configurée n'est pas détectée ? (y'a pas de page "réglages" pour les plugins que je sache)

Sinon ça peut être warning dans l'écran de configuration de l'ebook (même si ça ne parlera pas à quelqu'un de non-technique), en disant que l'impression sera faite sur une base du "meilleur effort" par un outil mutualisé.

@mrflos n'importe quel YesWiki pourra y faire appel ? Ou y'a un principe de "liste autorisée" de YesWiki qui pourront appeler https://coop.tools/ ?

J'imagine que `https://coop.tools/` sera/deviendra la valeur par défaut de la clé de config `htmltopdf_url`? Et qu'au lieu d'appeler le handler `/pdf` local, il fera appel au handler `/pdf` du `htmltopdf_url`, avec en paramètres, la clé de config `htmltopdf_key` et l'URL `/preview` du contenu à transformer en PDF.

**Comment by mrflos** [comment]
en tant que mainteneur des sites sur le serveur qui héberge coop.tools j'ai un peu peur de la surcharge si par défaut les milliers de yeswiki installés arrivent dessus...  
Pourrait on plutot faire un message d'erreur explicite et un renvoi sur une doc pour détailler l'installation?  
On pourra y mettre un formulaire de contact mail qui propose de donner accès a notre instance coop.tools en nous donnant l'url du wiki.
Je préférerai pouvoir contrôler cela (et on pourrait remplacer la clé coté yeswiki sans serveur pdf par une config de liste autorisée pour les yeswiki comme coop.tools qui seraient configurés pour permettre des acces externes)

**Comment by oncletom** [comment]
OK, ces personnes font la demande et ajustent la configuration par retour de mail.

**Comment by SuperSoniqueFr** [comment]
Bonjour, je me permet de vous contacter car nous utilisons yeswiki dans notre coopérative en Touraine.
Nous aurions besoin d'un "chromium" pour générer des pdf de nos yeswikis.
Peut-on échanger sur le sujet ?
Merci de votre retour

**Comment by J9rem** [comment]
Bonjour @SuperSoniqueFr ,

_J'ai relayé la demande sur notre canal concernant les demandes d'accompagnement sur Framateam, on verra si ça prend._

En attendant, je suis en train d'améliorer la documentation de l'extension `publication`. Peut-être n'avez-vous pas encore vu le contenu du fichier `README.md` , ... en tout cas, dans cet autre document déjà officiel, vous pouvez trouver quelques informations concernant l'installation de `chromium` : https://github.com/YesWiki/yeswiki-extension-publication/blob/master/docs/fr/README.md#configuration-de-lextension

**Comment by SuperSoniqueFr** [comment]
Bonjour Jérémy, 

 

Merci de votre retour.

J’ai déjà fait un tour dans la doc mais nous n’avons pas de serveur dédié, et donc ne pouvons installer Chromium, d’où ma demande.

J’espère que ma demande « prendra ».

 

Bon lundi !

Marc Orione pour https://odyssee-creation.coop

 

De : Jérémy Dufraisse ***@***.***> 
Envoyé : jeudi 1 décembre 2022 09:09
À : YesWiki/yeswiki-extension-publication ***@***.***>
Cc : SuperSoniqueFr ***@***.***>; Mention ***@***.***>
Objet : Re: [YesWiki/yeswiki-extension-publication] Meilleure gestion de l'appel à la librairie chromium (#11)

 

Bonjour @SuperSoniqueFr <https://github.com/SuperSoniqueFr>  ,

J'ai relayé la demande sur notre canal concernant les demandes d'accompagnement sur Framateam, on verra si ça prend.

En attendant, je suis en train d'améliorer la documentation de l'extension publication. Peut-être n'avez-vous pas encore vu le contenu du fichier README.md , ... en tout cas, dans cet autre document déjà officiel, vous pouvez trouver quelques informations concernant l'installation de chromium : https://github.com/YesWiki/yeswiki-extension-publication/blob/master/docs/fr/README.md#configuration-de-lextension

**Comment by J9rem** [comment]
Bonjour marc @SuperSoniqueFr ,

avez-vous la possibilité d'écrire à contact@yeswiki.net pour faire la demande officielle ?

**Comment by SuperSoniqueFr** [comment]
Ok je m’en occupe.Merci Jérémy !
    	Envoyé à partir de Outlook pour iOS
    
  

 De : Jérémy Dufraisse ***@***.***>Envoyé : lundi, décembre 12, 2022 09:32À : YesWiki/yeswiki-extension-publication ***@***.***>Cc : SuperSoniqueFr ***@***.***>; Mention ***@***.***>Objet : Re: [YesWiki/yeswiki-extension-publication] Meilleure gestion de l'appel à la librairie chromium (#11) 

Bonjour marc @SuperSoniqueFr ,

avez-vous la possibilité d'écrire à ***@***.*** pour faire la demande officielle ?
