### ISSUE TITLE
Ajout de paramètres supplémentaires lors de la création de l'ebook

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki-extension-publication#12]
par ex pouvoir indiquer que les ebook générés à cet endroit seront d'office en A4 et ce que param passe au-dessus de tous ceux fournis ailleurs ou avant.

et peut-être (mais c'est peut-être du rêve) : déjà imposé l'ebook pour une impression A4 avec pli central pour version livret A5 ou ...

**Comment by oncletom** [comment]
C'est quoi la différence avec #8 ?

**Comment by mrflos** [comment]
De ce que j'en comprend, #8 c'est avoir des classes css génériques définies pour styler dans les fiches et page wiki avec ces classes.  
Ici c'est changer un paramètre passé a l'action du générateur pour que par défaut le pdf généré soit a une certaine taille, (ou certain style css)

**Comment by gatienbataille** [comment]
oui c'est ça. si on dit rien ça part en A4 et ça respecte mise en page des fiches de l'ebook (et donc les éventuels styles css particuliers ajoutés #8) MAIS si on active ce param alors il prend le dessus ... mais en effet c'est pas sûr que ce soit pertinent (en le réécrivant là ;-)
