### ISSUE TITLE
Feature Request, idée de Romain : fonction panier 

### ISSUE THREAD

**Issue by mrflos** [YesWiki/yeswiki-extension-publication#14]
@RomainLalande propose (@oncletom ne pas en tenir compte)

Hello,

En testant publication, je me suis dit qu'une piste intéressante d'évolution serait de pouvoir en naviguant sur un wiki ajouter avec un "+" à coter des fiches les fiches que l'on veut ajouter dans son panier, qui sont ainsi sauvegardée quand on va sur la page qui génère l'ebook.
Un peu comme e l'e-commerce quoi x)

Voilà voilà !

**Comment by gatienbataille** [comment]
très chouette idée ! gardons ça comme une feature

**Comment by oncletom** [comment]
En rediscutant avec Romain (je crois ?), ça a été explicité dans #17.

Livraison… demain ;-)

**Comment by oncletom** [comment]
Je ferme, suite à l'implémentation dans #17. Et à sa future amélioration dans #31.
