### ISSUE TITLE
Le saut de page est intégré comme page à inclure, et non comme une macro

### ISSUE THREAD

**Issue by oncletom** [YesWiki/yeswiki-extension-publication#15]
Aujourd'hui, un saut de page est ajouté dans le corps de page comme suit : 

```
{{include page="{{pagebreak}}" class=""}}
```

L'attente est qu'il soit inclut plutôt comme ça : 

```
{{pagebreak}}
```

---

Exemple complet de ce qui cloche
```
{{include page="Tag1" class=""}}
{{include page="{{pagebreak}}" class=""}}
{{include page="Tag2" class=""}}
```

Exemple complet de ce qui est attendu : 

```
{{include page="Tag1" class=""}}
{{pagebreak}}
{{include page="Tag2" class=""}}
```

**Comment by gatienbataille** [comment]
oui c'est bien ça comme possibilité
mais quel serait le comportement "par défaut" si une page wiki ne contient pas ce {{pagebreak}}
(genre un ancien wiki ou un wiki construit par des "simple user")
