### ISSUE TITLE
Transformer un résultat interactif de `{{bazar vue="consulter"}}` en publication

### ISSUE THREAD

**Issue by oncletom** [YesWiki/yeswiki-extension-publication#17]
- Ajouter un script sur une vue bazar/bazarliste
- Ce script ajoute un lien à la suite des résultats, qui relie vers une page connue qui contient une action `{{ebookgenerator}}` (aka "page Ebook")
- L'URL vers la "page Ebook"contient la liste des tags correspondant aux items visibles de la liste (`$('.bazar-entry[data-id_fiche]:not([class*="icon"]):visible').toArray().map(element => element.dataset.id_fiche).join(',')`)
- La "page Ebook" interprète le paramètre d'URL comme un paramètre `chapterpages`, et pré-remplit la liste des pages en fonction
- Tenter avec un webcomponent, pour le fun

![image](https://user-images.githubusercontent.com/138627/93915160-e235da80-fd07-11ea-8526-cb17b6047b73.png)

Version minimale : 
```
{{bazar-to-ebook page="Ebook"}}
```

En personnalisant le libellé et l'icône : 
```
{{bazar-to-ebook page="Ebook" class="fas fa-book" label="Exporter en ebook" }}
```

**Comment by gatienbataille** [comment]
pas encore testé sous dory 23 oct

**Comment by oncletom** [comment]
Yes. Et ce qui est écrit dans l'issue n'est plus à jour. Ce qui est dans le [README temporaire](https://github.com/oncletom/yeswiki-extension-ebook/tree/feature/wiki-styles#action-bazar2publication) l'est — sauf erreur.
