### ISSUE TITLE
Intégrer les exports pdf et epub dans les exports de showExportButtons

### ISSUE THREAD

**Issue by GDoukhan** [YesWiki/yeswiki-extension-publication#2]

**Comment by oncletom** [comment]
J'avoue, l'intitulé de l'issue ne me parle pas.
Ça veut dire quoi ? Qu'est-ce qu'il se passe quand on clique sur X, depuis la page Y ?

**Comment by gatienbataille** [comment]
je crois que cette issue date un peu et n'est plus trop en phase avec "l'aujourd'hui" ;-)

**Comment by oncletom** [comment]
Je ferme ; à réouvrir si ça redevient d'actualité 👍
