### ISSUE TITLE
Documenter les paramètres d'actions

### ISSUE THREAD

**Issue by oncletom** [YesWiki/yeswiki-extension-publication#24]
Cf. YesWiki/yeswiki#498

Ça rendra les actions plus faciles à remplir, sans avoir à jeter un œil à la documentation (qui n'existe pas encore sur yeswiki.net).

- [ ] créer un fichier `actions/documentation.yaml`
- [ ] documenter l'action `{{publicationgenerator}}`
- [ ] documenter l'action `{{publicationlist}}`
- [ ] documenter l'action `{{bazar2publication}}`
- [ ] documenter l'action `{{blankpage}}`
- [ ] documenter l'action `{{pagebreak}}`
- [ ] documenter l'action `{{publication-template}}`
- [ ] documenter l'action `{{publication-cover}}`

**Comment by gatienbataille** [comment]
Salut, 
pourrais tu me dire s'il est possible d'utiliser dans une page wiki (ou dans la structure d'un formulaire) l'action {{pagebreak}} pour forcer le saut de page lorsque le user active le /pdf ou lors de la generation de l'ebook. 
Je me pose notamment cette question dans le cadre d'un formulaire long dont j'aimerais dès la conception prévoir les sauts de page pour gérer au mieux le rendu ebook. 

Genre envisager un truc dans le genre
`titre***{{bf_nom}}  - {{bf_code}}***Titre Automatique***`
`texte***bf_nom***Titre de la fiche*** *** *** *** ***text***1*** *** *** * *** * *** *** ***`
`texte***bf_code***code du parcours***3***3*** *** ***text***1*** *** *** * *** * *** *** ***`
`image***bf_image***Image***140***140***600***600***right***1*** *** *** * *** * *** *** ***`
`{{pagebreak}}`
`textelong***bf_description***Présentation du parcours proposé<br>*** ***10*** *** ***wiki***1*** *** *** * *** * *** *** ***`
`texte***bf_version***Année de création<br>*** *** *** *** ***text***0*** *** *** * *** * *** *** ***`
`textelong***bf_concepteurs***Créateurs de ce parcours<br>*** *** *** *** ***wiki***1*** *** *** * *** * *** *** ***`

**Comment by oncletom** [comment]
C'est carrément fait pour !

Tu trouveras les [actions disponibles dans le README temporaire](https://github.com/oncletom/yeswiki-extension-ebook/tree/feature/wiki-styles#actions-yeswiki).

**Comment by gatienbataille** [comment]
Super, j'essaie alors 
je ne parviens pas encore très bien à voir comment je peux placer cette action dans le formulaire pour qu'elle soit "comprise" par le formulaire : @mrflos tu me diras mais si je me souviens bien, ça parait pas possible en l'état... selon moi tout ce qui est pas "prévu" par le formulaire n'est pas interprété (comme du texte par exemple glissé dans le formulaire) ou alors y a un truc que je découvre ;-) 
en tout cas si on peut glisser ce genre d'action dans la structure des formulaires, ça va bcq aider !

**Comment by oncletom** [comment]
Très juste !

Tu trouveras un exemple sur https://pnth-terreenaction.dev.détour.studio/?LesProjets/raw
