### ISSUE TITLE
Proposer un handler générant du fichier modifiable type odt

### ISSUE THREAD

**Issue by GDoukhan** [YesWiki/yeswiki-extension-publication#3]

**Comment by oncletom** [comment]
OpenOffice/LibreOffice sait déjà importer du HTML, quel est le besoin derrière une sortie en ODT ?

**Comment by gatienbataille** [comment]
tout pareil ;-) je crois que cette issue date un peu et n'est plus trop en phase avec "l'aujourd'hui"

**Comment by oncletom** [comment]
Je ferme ; à réouvrir si ça redevient d'actualité 👍 

Possiblement hors périmètre… sauf à utiliser un logiciel externe type "pandoc", ou autre qui soit fréquemment disponible sur des hébergements mutualisés.
