### ISSUE TITLE
Deux types de Publications différentes donnent le même résultat

### ISSUE THREAD

**Issue by thom4parisot** [YesWiki/yeswiki-extension-publication#35]
Par ex, sur https://pnth-terreenaction.dev.détour.studio/?LesProjets, quand je click sur le bouton `{{bazar2publication}}` j'ai le même résultat qu'en cliquant sur `Export page to pdf`.

C'est surement lié au fait que je n'utilise pas les paramètres d'URL dans la clé de cache.

Le PDF "existe" donc il est proposé au téléchargement, plutôt que d'être créé.

**Comment by J9rem** [comment]
normalement corrigé par https://github.com/YesWiki/yeswiki-extension-publication/commit/b9dc337ffc4995a941751564a9cb36d611577f73
