### ISSUE TITLE
Rendre bazar2publication compatible avec dynamique

### ISSUE THREAD

**Issue by EdmondAgate** [YesWiki/yeswiki-extension-publication#50]
Bazar2publication ne fonctionne pas avec les templates dynamiques list et map

**Comment by J9rem** [comment]
fixed by https://github.com/YesWiki/yeswiki-extension-publication/tree/fix-bazar2publication

**Comment by J9rem** [comment]
fix by https://github.com/YesWiki/yeswiki-extension-publication/commit/b9dc337ffc4995a941751564a9cb36d611577f73
