### ISSUE TITLE
Mettre à jour vers pagedjs@0.1.40

### ISSUE THREAD

**Issue by oncletom** [YesWiki/yeswiki-extension-publication#6]
https://www.npmjs.com/package/pagedjs/v/0.1.40

Fichiers récupérables là aussi https://unpkg.com/browse/pagedjs@0.1.40/dist/

**Comment by oncletom** [comment]
Quelle "nouvelle" version ? `0.1.42` a été publiée il y a 2 jours: https://www.pagedjs.org/posts/2020-06-22-pagedjs-0-1-42/

Elle contient peut-être un fix pour la "première page", d'ailleurs.

Au passage, @mrflos tu disais que si un fichier `package.json` était ajouté à la racine, c'était pris en compte par l'outillage qui package les extensions ?

**Comment by mrflos** [comment]
non, hélas, ca marche pour composer.json , mais pas pour npm..
j'ai mis a jour vers 0.1.41.. je commite vers la version 0.1.42 a la mano, on verra plus tard pour gérer plus proprement
