### ISSUE TITLE
Meilleure respect de la mise en page lors du /pdf

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki-extension-publication#7]
Actuellement, lorsque l'on utilise le /pdf (ou son équivalent en bas de page) un pdf est généré. Il ne respecte pas le rendu graphique de la page.  L'idée serait que le pdf généré respecte au mieux la mise en page existante en coupant si besoin avec un beau saut de page. (presque comme un screenshot).

**Comment by oncletom** [comment]
OK donc ce que j'en comprends, c'est qu'on aimerait pouvoir récupérer les styles du thème YesWiki dans la page imprimée.

Les styles typographiques et de mise en page (genre les tableaux, et autres composants type légendes d'image, etc.), mais sans la partie décoration (entête, menus & cie).

**Comment by mrflos** [comment]
je confirme! et pour info, YesWiki a 2 handlers d'url : 
- **/iframe**, par exemple https://monsite.fr/?PageWiki/iframe : le contenu de la page **sans les menus et entête / pied de page** et **styles css de la page chargés**
- **/html**, par exemple https://monsite.fr/?PageWiki/iframe : le contenu de la page **sans les menus et entête / pied de page** et **sans styles css**

**Comment by oncletom** [comment]
Ah cool, `/iframe` va être utile, en y rajoutant les JS de Paged, et les styles d'impression.

**Comment by mrflos** [comment]
et tu peux "hacker" le handler dans un plugin en ajoutant par exemple dans le dossier `/tools/publication/handlers/page/` le fichier `__iframe.php` . Tu pourras faire $this->addJavascriptFile('') et autres, ils seront chargés si tu fais /iframe et que le module est actif.
en gros le fichier `__iframe.php` est executé avant le handler /iframe et le fichier `iframe__.php` apres.

A ta dispo si besoin pour les subtilités bizarres de yeswiki, la doc dev sera concues en septembre, mais pas avant hélas, et on est tres maigres actuellement..

**Comment by oncletom** [comment]
[My YesWiki website - test.pdf](https://github.com/YesWiki/yeswiki-extension-publication/files/5029342/My.YesWiki.website.-.test.pdf)
