### ISSUE TITLE
Création de styles CSS d'adaptation à inclure (selon souhait) dans design du template ou formulaire

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki-extension-publication#8]
Afin de permettre aux gestionnaires du wiki d'avoir "un peu" la main sur le rendu généré via le /pdf, l'idée serait de créer quelques styles css utilisables (selon souhait) dans le design des formulaires et des templates de rendus. 
Genre : paysage-portrait ou A4-a5 ou image 100% widht ou saut de page ou ... (toutes bonnes idées bienveues ;-)

**Comment by oncletom** [comment]
Bonne idée pour les formats de papier, l'orientation de la page et les images à 100% de largeur.

Questions :

- y'a des images (de décoration, type de icônes) qui ne seraient pas à styler ? Et si oui, avec quelle(s) classe(s) CSS je les repère ? (ou inversement, est-ce qu'il y a une liste de classes CSS à cibler pour déterminer que ce seront ces images à mettre en pleine largeur ?)
- qu'entends-tu par "saut de page" ? Quelle action y mets-tu derrière ?

J'ai pas d'autre idée pour l'instant mais j'en rajouterai si à l'usage je vois des trucs pratiques et rapides à faire.

**Comment by mrflos** [comment]
pour info, on utilise par défaut bootstrap, qui rend les images responsive (classe .img-responsive )

**Comment by mrflos** [comment]
pour les sauts de pages, je croies que @gatienbataille veut qu'on utilise une syntaxe genre `<div class="page-break"></div>` pour "forcer" le saut de page

**Comment by gatienbataille** [comment]
c'est bien ça en effet pour le page-break !

**Comment by gatienbataille** [comment]
je pense notamment à un style css qqui pourrait (m')être bien utile. ce style permettrait de cacher une partie de la page lors de la création du pdf. ceci permettrait par ex lors du /pdf (mais PAS du /iframe car autre usage possible avec iframe) de cacher des parties de la page qui ne méritent pas d'être imprimées (ou qui "gacheraient" le rendu pdf) 
par ex il est possible d'appeler en bas des pages wiki une action qui crée un "fil" (page précédente - page suivante) mais qui est parfaitement inutile pour l'impression 
=> sur cette page par ex https://www.pnth-terreenaction.org/?PartageSincere si on devait l'imprimer en pdf, le partie "fil avant après" et le bloc jaune "ces pages pourraient vous intéresser" ne servent à rien dans le pdf (mais sont par contre utile dans le /iframe)

**Comment by oncletom** [comment]
Je peux supprimer facilement le "ces pages pourraient vous intéresser", si ce sont les derniers éléments d'un contenu inclus. Sachant que le style est appliqué à la main (j'ai vu que ce sont des `<div class="well">...</div>` écrits à même le corps de page).

Je propose ça parce que j'ai aussi vu des contenus qui sont stylés de la même manière, à d'autres endroits du corps de page.

**Comment by gatienbataille** [comment]
Salut oui l'idée de pouvoir appliquer un style spécial "cache ça en mode print" est très très intéressant (utile) 
l'ajout de petit bout de code css est assez régulier dans yeswiki même si on essaie de le limiter à quelques "trucs" tout faits, cela dit c'est un des avantages de yeswiki (en tout cas aimés par les users avancés)

**Comment by gatienbataille** [comment]
je pense aussi au fait que certains code yeswiki comme {{accordion}} par ex devraient être interprétés lors de la demande du pdf et par exemple dans la cas de l'accordion ouvrir celui-ci pour en imprimer le contenu aussi et pas juste son "bandeau titre"

**Comment by oncletom** [comment]
Bonne idée !

Tu as une URL de page qui en contient un ?
Et est-ce que tu penses à d'autres éléments dynamiques comme ça qui mériteraient un traitement particulier lors de leur passage en print ?

**Comment by gatienbataille** [comment]
eheh je commence à comprendre le trucs du "quand on ouvre la boîte, on a rarement une idée de tout ce qui va en sortir ;-)" (comme tentait de me l'expliquer @mrflos sur le dév informatique)

donc pour page accordion, j'ai celle-ci https://www.pnth-terreenaction.org/?RapportTemps mais dis moi si elle était dans le pack .zip fourni

du coup en plus de accordion, je pense à ces possibilités  : 
 - quand on insère un fichier mp3, il est interprété et met un bandeau lecteur (on en fait quoi du coup ? on peut imprimer le bandeau lecteur me concernant et peut-être même le rendre "actif" dans le pdf ???)
 - l'incruste d'une vidéo via iframe => devient une image dans le print ? reste clicable dans le pdf ? 
 - en fait l'iframe de n'importe quoi est possible dans yeswiki... => on en fait quoi ? à mon avis ça pose des soucis (la vidéo a une taille mais si on inscruste une page web... chaud)
 - carte mentale : si on insère un fichier freeplane, il est interprété et affiche contenu de la carte sans possibilité de la modifier => on en fait quoi ? on imprime ? oui selon moi
 - il est possible d'utiliser une action {{nav}} qui génère des onglets sur la page => du coup, quel comportement ? => selon moi : chaque contenu de nav vient se mettre en dessous du précédent après un saut de ligne bien propre ;-) tu trouves un exemple dans la roue crantée / gestion du site
 - pour mention mais je sais pas si ça joue : il est possible d'appeler le contenu d'une page wiki dans une autre page wiki via {{include page="NomPageWiki"}} => selon moi, on print le contenu importé comme si il faisait partie de la page qui l'accueille

euh pour l'instant je pense à ça ;-) il y a sans doute plus mais ça me semble être le principal

**Comment by gatienbataille** [comment]
je pense aussi à ça 
{{backgroundimage height="150" file="monbandeau.jpg" class="white text-center doubletitlesize"}}
=====Texte du titre=====
description
{{endbackgroundimage}}
