### ISSUE TITLE
Meilleure gestion du chapitrage + page de couverture et de fin

### ISSUE THREAD

**Issue by gatienbataille** [YesWiki/yeswiki-extension-publication#9]
Lorsqu'on utiliise l'outil publication pour générer un ebook et que l'on y place des pages chapitre on rencontre : 
- la génération "peu fidèle" en pdf du design réalisé sur la page chapitre (voir issues #7)
- son insertion étrange dans le flux de pages de l'ebook généré (saut de page étrange)
 - la création automatique d'un verso de chapitre vierge (une page blanche dans le flux)
 
La page couvreture devrait automatiquement créer page verso vierge et insérer une feuille RV de garde vierge.
Ensuite viendrait s'insérer automatiquement une [page de grand titre](https://fr.wikipedia.org/wiki/Page_(livre) : càd une page contenant le nom de l'auteur, le titre de l'œuvre, et autres infos fournies (si fourni : prévu dans l'outil publication). Au verso de cette page (si infos fournies / n'existe pas pour l'instant dans l'outil publication !!! ) se trouveraient les données de catalogage, d'ISBN et de copyright.

Ensuite le premier chapitre et c'est parti 

La page de couverture comprendrait d'abord une page vierge et au verso la page de couverture fournie (c'est demandé via l'outil publication)

**Comment by mrflos** [comment]
une page chapitre, c'est dans les options du générateur, on peut définir des pages wikis qui seront automatiquement présentes et qui permettent de délimiter des chapitres (on déplace les contenus sélectionnés avant ou apres chaque chapitre avec de générer) les contenus.

Je croies que l'idée de @gatienbataille c'est d'utiliser les metadonnées de l'ebook généré pour avoir automatiquement dans les premieres pages une infos type date de parution, auteur, etc, comme dans les vrais livres ;).
 Je ne suis pas commanditaire, mais je me dis que ce serait à affiner, car utile dans le cas de l'écriture d'un livre mais pas pour des newsletters ou autre publications.
Cela devrait etre une action wiki a ajouter si besoin, a mon humble avis.

**Comment by gatienbataille** [comment]
yop, bien vu sur le côté newsletter (que je connais pas via ebook donc pas pirs en compte) mais oui alors "à prendre en compte".  ce que je voulais exprimer c'est que dans un (e)book, y a toujours un certains nombres de pages "par défaut" (couvrture, puis page blanche, puis page avec juste le titre-auteur-date, puis de nouveau une page blanche...) et que ce serait cool si ça pouvait se générer tout seul .
Idem aussi pour page chapitre, actuellement via la page wiki désignée on crée une page chapitre avec un peu de mise en page mais ça génère pas automatiquement une page blanche juste derrière la page chapitre (ce qui est nécessaire si à un moment on veut "imposer" le book pour en faire un livret) 
mais c'est juste proposition (et sans doute à pouvoir activer si besoin pour permettre la création des newsletters) / je sais pas si c'est clair...

**Comment by mrflos** [comment]
yes, c'est clair, pour ma part je serais pour documenter et proposer des codes tout fait pour insérer les pages avec les notions pour des ebook par du code html a copier coller dans la bonne page ou des mécanismes si l'on choisit ebook plutot que newsletter.  
On peut continuer a faire des specs par discussions, mais je me sentirais de faire cette tache, si jamais les autres prennent trop de temps à @oncletom , et donc la mettre en priorité basse par rapport aux autres.

**Comment by gatienbataille** [comment]
> On peut continuer a faire des specs par discussions, mais je me sentirais de faire cette tache, si jamais les autres prennent trop de temps à @oncletom , et donc la mettre en priorité basse par rapport aux autres.

ok moi j'ai un enjeu assez fort sur la génération d'ebook et pdf propres avant newsletter dans ce projet (en tout cas j'ai plutot défendu ebook et pdf quand j'ai été cherché budget ,-)

**Comment by gatienbataille** [comment]
trouver ça dans la doc
Pour générer des newsletters

Avant de pouvoir générer des newsletters, il faut créer un formulaire bazar suivant avec la structure suivante :

texte***bf_titre***Titre***60***255*** *** *** ***1***0***
texte***bf_description***Description***60***255*** *** *** ***0***0***
texte***bf_author***Auteur***60***255*** *** *** ***0***0***
textelong***bf_content***Contenu de la newsletter***20***20*** *** ***html***1***0***

Un fois ce formulaire créé, il faut trouver son id et utiliser l'action {{publicationgenerator}} avec, au minimum les paramètres suivants :

    outputformat="newsletter"
    formid="<id du formulaire>"

Soit, au minimum : {{publicationgenerator outputformat="newsletter" formid="<id du formulaire>"}}

Chaque newsletter générée sera enregistrée sous la forme d'une fiche bazar du formulaire <id du formulaire> sur le wiki.

**Comment by oncletom** [comment]
Okay merci ! Donc ça génère une newsletter, au format PDF, qui est envoyée à la mano (?) — et donc pas vraiment affichée/téléchargée par le public sur le site.

J'imagine que ce qui permet de distinguer un contenu imprimable "ebook" et "newsletter", c'est ce fameux "formid".

@mrflos c'est une information qui se récupère via une méthode/fonction ?

**Comment by mrflos** [comment]
hello, 
En effet, l'action de générer un ebook ou une newsletter ne fait que générer soit une page pour l'ebook, avec des includes du contenu des pages sélectionnées (qui pourront etre modifiées a postériori), soit une fiche bazar (figée et modifiable par la suite indépendamment).  
Par contre il suffit de faire /pdf pour générer le pdf, ou /mail pour l'envoyer par mail.  

Et en effet le paramètre `formid` pourrait être discriminant, mais il existe aussi un paramètre `outputformat` qui si non précisé prend Ebook par défaut.  
Dans le cas ou l'on précise `outputformat="newsletter"`, il faut aussi préciser `formid="<id form>"`.  

Le readme de l'extension publication est assez complet sur les paramètres disponibles.

Et donc pour la méthode, dans l'action publicationgenerator, tu peux faire : 
```php
$outputFormat = $this->getParameter('outputformat');
if ($outputFormat == 'newsletter') {
  // CODE
}
```

Ailleurs, tu peux vérifier l'existance du triple fiche_bazar (donc si c'est un fiche, c'est une newsletter) ou la présence de métadonnées ebook aussi dans les triples (mais je ne voies pas bien ouo cela servirai..)

**Comment by gatienbataille** [comment]
lien fait avec  #16 suite à réunion avec @oncletom
